from transformers import pipeline

pipe = pipeline("summarization")

text = """
Monkeys, belonging to the primate order, offer a captivating glimpse into the rich diversity of the animal kingdom. Renowned for their agility, intelligence, and social behaviors, monkeys have long been subjects of fascination for scientists, nature enthusiasts, and the general public alike. \n One of the most distinctive features of monkeys is their anthropoid characteristics, resembling humans in many aspects. With expressive faces, dexterous hands, and the ability to walk on hind limbs, they often evoke a sense of familiarity. The diversity within the monkey species is vast, ranging from the tiny pygmy marmoset to the powerful and larger primates like baboons and macaques. \n Monkeys are highly social creatures, forming intricate communities with well-defined hierarchies. These social structures play a crucial role in their survival, as cooperation and communication are essential for navigating their complex environments. Observing monkey troops reveals a spectrum of behaviors, from grooming rituals that strengthen social bonds to playful activities that serve both recreational and educational purposes. \n Intelligence is a hallmark of monkeys, evident in their problem-solving skills, tool usage, and capacity for learning. Some species exhibit an impressive level of cognitive abilities, comparable to that of certain non-human primates. Their ability to adapt to changing circumstances and environments underscores the versatility of these remarkable creatures. \n The playful antics of monkeys, swinging from tree branches, engaging in communal games, and showcasing acrobatic prowess, never fail to entertain and evoke a sense of wonder. However, the conservation status of various monkey species is a cause for concern, as habitat loss, deforestation, and illegal wildlife trade threaten their populations. \n In conclusion, monkeys stand as captivating ambassadors of the animal kingdom, offering insights into the wonders of nature. Their intelligence, social behaviors, and playful nature make them not only a subject of scientific interest but also a source of inspiration and admiration for those who appreciate the intricacies of the natural world. As we delve deeper into understanding and protecting these creatures, we unlock the potential for a harmonious coexistence with the diverse life forms that share our planet.
"""

summary = pipe(text)[0]['summary_text']

print(summary)